### ISSUE TITLE
storage：自从上次快照以来，所有的持久化条目；

### ISSUE THREAD

**Issue by gopherWxf** [sakura-ysy/TinyKV-2022-doc#1]
project2：这里的“持久化条目”是什么意思，被commit的日志？还是快照的日志？另外可以留个联系方式嘛~

**Comment by sakura-ysy** [comment]
都不是hhhh。
首先我们要明确 commit 和 snapshot 两者是什么。
commit：一旦某一个日志在集群中被大多数节点同步了，那么它就算作被 commit 了。那有什么用呢？被 commit 的日志，才可以进行 apply，所谓 apply，就是执行日志中包含的命令（比如读写什么的）。也就是，只有被大多数节点同步的日志，才能执行，这样看来是不是更容易理解 commit 一些。它和持久化是没有直接关系的。
snapshot：为了防止节点 '存储' 了过多日志，加入快照功能。说白了就是把一些已经完成同步的日志直接给删了，然后把状态存下来，这样就可以避免日志累计过多。
上面说的 '存储' 一词，实际上就是持久化。在节点刚开始收到日志的时候，肯定是先暂存入内存中的，然后在集群中同步，这时的日志叫作未持久化。但这样，一旦节点没了，或者进程关了，那日志不就没了，所以不可能仅仅存在内存中。节点所有的日志，都要逐渐保存进磁盘，这样不论节点是死是活，日志都会留下来的，这时的日志叫作持久化。而 snapshot，就是为了避免存在磁盘中的日志过多，所以会删除一定的持久化日志并生成 snapshot。现在再来看这句话，“自从上次快照以来，所有的持久化条目”，意思就是在上次生成 snapshot 之后，磁盘中没有被删的日志。是不是好理解了一些。
什么时候持久化，这点会在 rawnode.go 进行 Advance 的时候来推进；怎么持久化，这点需要你在 peer_msg_handler.go 中实现。
我QQ：2575633193，欢迎交流hhh

**Comment by gopherWxf** [comment]
感谢
